### ISSUE TITLE
Billing Client 5.0.0 (latest) support

### ISSUE THREAD

**Issue by iguerendiain** [adaptyteam/AdaptySDK-Android#13]
After updating com.android.billingclient:billing to version 5.0.0 I get an error when activating Adapty.

Executing this:

`Adapty.activate(applicationContext, BuildConfig.ADAPTY_PUBLIC_KEY)
`
Throws the following exception:

```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: <<redacted>>, PID: 15847
    java.lang.NoSuchMethodError: No virtual method queryPurchases(Ljava/lang/String;)Lcom/android/billingclient/api/Purchase$PurchasesResult; in class Lcom/android/billingclient/api/BillingClient; or its super classes (declaration of 'com.android.billingclient.api.BillingClient' appears in /data/app/<<redacted>>/base.apk)
        at com.adapty.internal.data.cloud.StoreManager.queryInapps(StoreManager.kt:325)
        at com.adapty.internal.domain.PurchasesInteractor.consumeAndAcknowledgeTheUnprocessed(PurchasesInteractor.kt:140)
        at com.adapty.internal.AdaptyInternal.executeStartRequests(AdaptyInternal.kt:326)
        at com.adapty.internal.AdaptyInternal.access$executeStartRequests(AdaptyInternal.kt:26)
        at com.adapty.internal.AdaptyInternal$activate$1$2.invokeSuspend(AdaptyInternal.kt:133)
        at com.adapty.internal.AdaptyInternal$activate$1$2.invoke(AdaptyInternal.kt)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:136)
        at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1.emit(Collect.kt:136)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

I had to make lots of changes to the billing library's implementation so I guess this new version broke compatibility with older codebase. I assume the same is happening here with Adapty's library.

**Comment by vladd-g** [comment]
@iguerendiain Sorry, Adapty SDK 1.10.0 is not compatible with Billing Library 5. We're currently working on a newer version that supports the latest Billing Library

**Comment by eric6300** [comment]
Please support Billing Library 5. Thanks!

**Comment by andreas-remente** [comment]
We updated to the latest Adapty version and this issue disappeared (using Billing 5.1.0). I assume this was fixed at some point and that this issue can be closed?

**Comment by qwertyway** [comment]
Updating to Billing 5 is very crucial. Currently Adapty lib (for flutter) is incompatible with our apps...

**Comment by vladd-g** [comment]
We're in the final stage of migrating to the new Billing Library, so there's no need to worry. If you'd like, you can try our [beta version](https://search.maven.org/artifact/io.adapty/android-sdk/2.5.0-billing5-beta1/aar) (but please pay attention to the [description provided](https://github.com/adaptyteam/AdaptySDK-Android/releases/tag/2.5.0-billing5-beta1))

**Comment by vladd-g** [comment]
Version 2.6.0 supports the latest Billing Library, you can upgrade to it as follows:
`implementation 'io.adapty:android-sdk:2.6.0'`

Since it includes some breaking changes, please refer to the [migration guide](https://docs.adapty.io/docs/migrate-to-google-billing-library-v5)
