### ISSUE TITLE
Error: No virtual method: queryPurchases

### ISSUE THREAD

**Issue by Tiemichael** [adaptyteam/AdaptySDK-Android#17]
I saw an error looking identical #13 , and I have the same issue with Billing Library 4.0.0:

`2022-09-02 14:01:07.490 4561-4642/com.xxx.kotlin.yyy E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-7
    Process: com.xxx.kotlin.yyyy, PID: 4561
    java.lang.NoSuchMethodError: No virtual method queryPurchases(Ljava/lang/String;)Lcom/android/billingclient/api/Purchase$PurchasesResult; in class Lcom/android/billingclient/api/BillingClient; or its super classes (declaration of 'com.android.billingclient.api.BillingClient' appears in /data/app/~~0WjYuDHtimqEOLG92KbSxg==/com.xxx.kotlin.yyy-Hagu0E1CCgHh-5QFGefSTA==/base.apk)
        at com.adapty.internal.data.cloud.StoreManager.queryInapps(StoreManager.kt:325)
        at com.adapty.internal.domain.PurchasesInteractor.consumeAndAcknowledgeTheUnprocessed(PurchasesInteractor.kt:140)
        at com.adapty.internal.AdaptyInternal.executeStartRequests(AdaptyInternal.kt:326)
        at com.adapty.internal.AdaptyInternal.access$executeStartRequests(AdaptyInternal.kt:26)
        at com.adapty.internal.AdaptyInternal$activate$1$2.invokeSuspend(AdaptyInternal.kt:133)
        at com.adapty.internal.AdaptyInternal$activate$1$2.invoke(Unknown Source:10)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
        at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$2.emit(Errors.kt:158)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelli`

In my build.gradle:
`  implementation 'com.android.billingclient:billing:4.0.0'
    implementation 'com.github.adaptyteam:AdaptySDK-Android:1.12.0'`

This the first application I want to publish, and my very first attempt to integrate Adapty, so it might be some really stupid error. Also the sample app (from here) does not show this error, so I seems to be caused by a different reason.
Thanks!

**Comment by Tiemichael** [comment]
It seems I found the culprit:
I had an other billing client in my build.gradle "implementation 'com.github.akshaaatt:Google-IAP:1.2.4'",
which I never used in any kotlin code.
Removing this line, fixed the issue ...
Sorry for any inconvenience caused

**Comment by Tiemichael** [comment]
It seems I found the issue:
I had another IAP-implementation in my build.gradle "implementation 'com.github.akshaaatt:Google-IAP:1.2.4'", which is not used on any kotlin-file.
Removing it, and re-syncing gradle fixed the issue.
Sorry for any inconvenience

**Comment by vladd-g** [comment]
@Tiemichael glad you found the problem, actually in such cases you can run gradle task `app:dependencies` to see the actual versions of your deps

**Comment by Tiemichael** [comment]
I am surprised that an **unused** implementation can cause issues ...
