### ISSUE TITLE
Unable to get paywall with SDK version 2.0.0

### ISSUE THREAD

**Issue by jobe2018** [adaptyteam/AdaptySDK-Android#19]
I've just updated the Adapty SDK to the latest version 2.0.0 and now I'm unable to get any paywall:

```
unable to get paywall "xyz"
com.adapty.errors.AdaptyError: Play Market request failed: Google Play In-app Billing API version is less than 3
  at com.adapty.internal.data.cloud.StoreManager$startConnectionSync$$inlined$suspendCancellableCoroutine$lambda$1.onBillingSetupFinished(StoreManager.kt:352)
  at com.android.billingclient.api.zzaj.zzd(com.android.billingclient:billing@@4.1.0:1)
  at com.android.billingclient.api.zzaj.zza(com.android.billingclient:billing@@4.1.0:32)
  at com.android.billingclient.api.zzah.call(Unknown Source:2)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:919)
```

**Comment by vladd-g** [comment]
@jobe2018 is on a real device with Play Market, not on an emulator without Play?

**Comment by vladd-g** [comment]
could you please check on a real device?

**Comment by jobe2018** [comment]
I found out, why it was not working: I wasn't logged into my Google account on the emulator. After doing so everything works fine.
