### ISSUE TITLE
SDK version 2.8.0 crashes when api.adapty.io host name is not resolved

### ISSUE THREAD

**Issue by frankjoshua** [adaptyteam/AdaptySDK-Android#22]
Is there a way to catch this error instead of crashing?

`Fatal Exception: com.adapty.errors.AdaptyError: Request Error: Unable to resolve host "api.adapty.io": No address associated with hostname
       at com.adapty.internal.data.cloud.BaseHttpClient.newCall(BaseHttpClient.kt:39)
       at com.adapty.internal.data.cloud.CloudRepository.getViewConfiguration(CloudRepository.kt:59)
       at com.adapty.internal.domain.ProductsInteractor$getViewConfiguration$1.invokeSuspend(ProductsInteractor.kt:83)
       at com.adapty.internal.domain.ProductsInteractor$getViewConfiguration$1.invoke(ProductsInteractor.kt:1)
       at com.adapty.internal.domain.ProductsInteractor$getViewConfiguration$1.invoke(ProductsInteractor.kt:2)
       at com.adapty.internal.domain.AuthInteractor$runWhenAuthDataSynced$3.invokeSuspend(AuthInteractor.kt:115)
       at com.adapty.internal.domain.AuthInteractor$runWhenAuthDataSynced$3.invoke(AuthInteractor.kt:1)
       at com.adapty.internal.domain.AuthInteractor$runWhenAuthDataSynced$3.invoke(AuthInteractor.kt:2)
       at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:217)
       at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt:18)
       at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt:18)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:13)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:13)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
       at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.java:112)
       at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(BuildersKt__Builders_common.kt:56)
       at kotlinx.coroutines.BuildersKt.launch(Builders.kt:1)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(BuildersKt__Builders_common.kt:47)
       at kotlinx.coroutines.BuildersKt.launch$default(Builders.kt:1)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:33)
       at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$2.emit(Errors.kt:158)
       at kotlinx.coroutines.flow.FlowKt__BuildersKt$flowOf$$inlined$unsafeFlow$2.collect(SafeCollector.common.kt:114)
       at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(FlowKt__Collect.kt:109)
       at kotlinx.coroutines.flow.FlowKt.emitAll(Flow.kt:1)
       at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$1$1.emit(Merge.kt:83)
       at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$1$1.emit(Merge.kt:83)
       at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1$2.emit(Emitters.kt:223)
       at kotlinx.coroutines.flow.FlowKt__LimitKt.emitAbort$FlowKt__LimitKt(FlowKt__Limit.kt:73)
       at kotlinx.coroutines.flow.FlowKt__LimitKt.access$emitAbort$FlowKt__LimitKt(FlowKt__Limit.kt:1)
       at kotlinx.coroutines.flow.FlowKt__LimitKt$take$2$1.emit(Limit.kt:63)
       at com.adapty.internal.data.cloud.CloudRepository.onActivateAllowed(CloudRepository.java:177)
       at com.adapty.internal.data.cloud.CloudRepository$onActivateAllowed$$inlined$filter$1$2.emit(Collect.kt:135)
       at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
       at com.adapty.internal.data.cloud.CloudRepository$onActivateAllowed$$inlined$filter$1.collect(SafeCollector.common.kt:114)
       at kotlinx.coroutines.flow.FlowKt__LimitKt$take$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:116)
       at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1.collect(SafeCollector.common.kt:114)
       at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
       at kotlinx.coroutines.flow.FlowKt__ErrorsKt.catchImpl(FlowKt__Errors.kt:156)
       at kotlinx.coroutines.flow.FlowKt.catchImpl(Flow.kt:1)
       at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(Merge.kt:27)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt:13)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt:13)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
       at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(Merge.kt:25)
       at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
       at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt:6)
       at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)`

**Comment by vladd-g** [comment]
@frankjoshua thank you for the report! Looks interesting because it's never been a crash.

Could you please provide some details on how exactly have you encountered it? Can it be an `error` reported from the callback of custom `LogHandler`?

**Comment by frankjoshua** [comment]
Ok. I'm a little embarrassed. I was not handling the error from the suspendCoroutine in my code.

```
private suspend fun onPaywallSuccess(paywall: AdaptyPaywall) {
        val products = getAdadptyProducts(paywall)
        val viewConfig = getViewConfiguration(paywall)
        paywallViewModel.setAdaptyPaywall(PaywallHolder(paywall, products, viewConfig))
    }

    private suspend fun getViewConfiguration(paywall: AdaptyPaywall): AdaptyViewConfiguration {
        return suspendCoroutine { continuation ->
            Adapty.getViewConfiguration(paywall, "en") {result ->
                when(result){
                    is AdaptyResult.Success -> {
                        continuation.resumeWith(Result.success(result.value))
                    }
                    is AdaptyResult.Error -> {
                        continuation.resumeWith(Result.failure(result.error))
                    }
                }
            }
        }
    }
```
Sorry for the bother.
