### ISSUE TITLE
Crash related to missing WebView

### ISSUE THREAD

**Issue by parizene** [adaptyteam/AdaptySDK-Android#27]
Happens on Adapty init

Reproduced on Android 11, 12, 14
Devices: LGE K51S, Pixel 8 Pro, Galaxy S21 5G, TCL TAB 8 LE
Can also be reproduced on Android emulator with old Android

`Fatal Exception: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:398)
       at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1400)
       at com.adapty.internal.utils.UserAgentRetriever$retrieveUserAgent$1.invoke(UserAgentRetriever.kt:35)
       at com.adapty.internal.utils.UserAgentRetriever$retrieveUserAgent$1.invoke(UserAgentRetriever.kt:32)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)`

**Comment by vladd-g** [comment]
fixed in v2.9.2
