### ISSUE TITLE
Crash in release build - TTypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.

### ISSUE THREAD

**Issue by mirecalu** [adaptyteam/AdaptySDK-Android#28]
Lib version: `2.10.3`

With `minify = true` and proguard with `-keep class com.adapty.** { *; }` I encounter this crash:

```
java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6764)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
                                                                                                    	at ob.a.<init>(SourceFile:9)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$1$1.<init>(Unknown Source:0)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$1.invoke(SourceFile:25)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$1.invoke(SourceFile:1)
                                                                                                    	at com.adapty.internal.di.DIObject.provide(Unknown Source:26)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$17.invoke(SourceFile:4)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$17.invoke(SourceFile:1)
                                                                                                    	at com.adapty.internal.di.DIObject.provide(Unknown Source:26)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$15.invoke(SourceFile:5)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$15.invoke(SourceFile:1)
                                                                                                    	at com.adapty.internal.di.DIObject.provide(Unknown Source:26)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$7.invoke(SourceFile:7)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$7.invoke(SourceFile:1)
                                                                                                    	at com.adapty.internal.di.DIObject.provide(Unknown Source:26)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$5.invoke(SourceFile:5)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$5.invoke(SourceFile:1)
                                                                                                    	at com.adapty.internal.di.DIObject.provide(Unknown Source:26)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$47.invoke(SourceFile:5)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$47.invoke(SourceFile:1)
                                                                                                    	at com.adapty.internal.di.DIObject.provide(Unknown Source:26)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$48.invoke(SourceFile:5)
                                                                                                    	at com.adapty.internal.di.Dependencies$init$48.invoke(SourceFile:1)
                                                                                                    	at com.adapty.internal.di.DIObject.provide(Unknown Source:26)
                                                                                                    	at com.adapty.Adapty$special$$inlined$inject$adapty_release$default$1.invoke(Unknown Source:23)
                                                                                                    	at ae.o.getValue(Unknown Source:11)
                                                                                                    	at com.adapty.Adapty.getAdaptyInternal(Unknown Source:2)
                                                                                                    	at com.adapty.Adapty.init(Unknown Source:23)
                                                                                                    	at com.adapty.Adapty.activate(SourceFile:16)
                                                                                                    	at com.adapty.Adapty.activate$default(Unknown Source:10)
                                                                                                    	at com.mirecalu.finario.application.FinarioApplication.onCreate(Unknown Source:51)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6759)
```

➡️ I've solved it by adding `-keep class com.google.gson.reflect.TypeToken { *; }`  but I don't understand why I'm the only one having this issue 🧐

**Comment by vladd-g** [comment]
hi @mirecalu, so now everything works fine?

**Comment by mirecalu** [comment]
Yes :) I think it could be a good idea to update the documentation or fix the lib so it doesn't happen again

**Comment by al-tush** [comment]
I faced the same problem today after upgrading to Flutter 3.24. Hi friend )
