### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.optString(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by krottv** [adaptyteam/AdaptySDK-Android#5]
When calling Adapty.restorePurchases. I use the last version of adapty lib.
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.optString(java.lang.String)' on a null object reference
        at com.android.billingclient.api.SkuDetails.getDescription(com.android.billingclient:billing@@3.0.2:1)
        at com.adapty.api.entity.restore.RestoreItem.setDetails(RestoreItem.kt:42)
        at com.adapty.purchase.InAppPurchases.fillProductInfoFromCache(InAppPurchases.kt:270)
        at com.adapty.purchase.InAppPurchases.access$fillProductInfoFromCache(InAppPurchases.kt:18)
        at com.adapty.purchase.InAppPurchases$queryPurchaseHistory$1.onPurchaseHistoryResponse(InAppPurchases.kt:225)
        at com.android.billingclient.api.zzj.run(com.android.billingclient:billing@@3.0.2:1)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by vladd-g** [comment]
@krottv Thanks for the report, strange NPE in Google's billing library, we're researching why it is happening.

**Comment by krottv** [comment]
@vladd-g Happens on each call, so app crashes at start-up. The issue is critical. It fixes only after cleaning up app's data/cache

**Comment by vladd-g** [comment]
@krottv Did you notice how it happened? I mean were your app crashing on start from the very first time, or it was okay initially and started crashing after specific actions? Did this crash happen again after clearing app's data?

Purchases get synced with Adapty backend under the hood on every app launch. You need to manually call restorePurchases() only if you're using Adapty in observer mode, https://docs.adapty.io/sdk/integrating-adapty-sdk/android-sdk-intro/android-sdk-observer-mode

**Comment by krottv** [comment]
@vladd-g 
It seems that crashes started after I uploaded new version of the app on my device. And then it crashed on every start-up. After cleaning app's data the crash never happened again.
But I was able to reproduce the scenario a few times.

**Comment by vladd-g** [comment]
@krottv Did both versions of the app have the same version of Adapty library?

"But I was able to reproduce the scenario a few times." - you mean after clearing data and without reinstalling? Or you installed the previous version again, then the new version, and that was the way you reproduced the crash?

**Comment by krottv** [comment]
@vladd-g 
I reproduced by installing old version again, and updating it to the new version. The old version didn't have Adapty at all, it had https://github.com/serso/android-checkout. The new version has Adapty 0.8.4

**Comment by krottv** [comment]
@vladd-g 
I cought a similar crash when calling `Adapty.getPurchaserInfo`

When I updated debug version of the app to release (both had adapty 0.8.6). Seems like it is not very hard to fix. Just introduce additional null check.

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.optString(java.lang.String)' on a null object reference
        at com.adapty.api.entity.restore.RestoreItem.setDetails(RestoreItem.kt:3)
        at com.adapty.purchase.InAppPurchases.fillProductInfoFromCache(InAppPurchases.kt:6)
        at com.adapty.purchase.InAppPurchases.access$fillProductInfoFromCache(InAppPurchases.kt:1)
        at com.adapty.purchase.InAppPurchases$queryPurchaseHistory$1.onPurchaseHistoryResponse(InAppPurchases.kt:28)
        at a.d.a.a.q.run(com.android.billingclient:billing@@3.0.2:361)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

```

**Comment by vladd-g** [comment]
@krottv 
It may be an obfuscation issue, please try adding `-keep class com.android.billingclient.** { *; }` to your proguard config

**Comment by vladd-g** [comment]
@krottv could you please check this error on 1.1.0 (if still occurs, then with suggestion from my previous comment) so that I can close the issue?

**Comment by krottv** [comment]
The issue is gone.
